name: ci

on:
  push:
    branches:
      - "main"

jobs:
    buildarm64:
        runs-on: ubuntu-latest
        steps:
          -
            name: Checkout
            uses: actions/checkout@v3
          # Setup to bulid arm based container since the actions run on x86 machines.
          -
            name: Set up QEMU
            uses: docker/setup-qemu-action@v2
          -
            name: Login to Docker Hub
            uses: docker/login-action@v2
            with:
              registry: ghcr.io
              username: ${{ github.actor }}
              password: ${{ github.token }}
          -
            name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v2
          -
            name: Build and push arm64
            uses: docker/build-push-action@v3
            with:
              context: .
              file: ./Dockerfile
              platforms: linux/arm64
              push: true
              tags: ghcr.io/the-renee-project/image-classifier-demo:latest